#!/usr/bin/env fish
#
# install-global.fish — Creates a global "lyrics-sync" fish function so
# you can run the program from ANY directory/session, no matter where
# this project folder lives. It works by resolving the project's
# absolute path once (right now) and baking it into a small function
# file that fish auto-loads in every new session — no daemon, no
# background process, just a normal command.
#
# Usage:
#   chmod +x install-global.fish
#   ./install-global.fish
#
# Afterwards, from any new fish shell, anywhere:
#   lyrics-sync

set SCRIPT_DIR (realpath (dirname (status --current-filename)))
set FUNC_DIR "$HOME/.config/fish/functions"
set FUNC_FILE "$FUNC_DIR/lyrics-sync.fish"

if not test -f "$SCRIPT_DIR/run.fish"
    echo "Could not find run.fish next to this script at: $SCRIPT_DIR"
    exit 1
end

if not test -d "$SCRIPT_DIR/venv"
    echo "Virtual environment not found at: $SCRIPT_DIR/venv"
    echo "Run ./install.sh inside the project folder first."
    exit 1
end

mkdir -p "$FUNC_DIR"

echo "==> Creating fish function at: $FUNC_FILE"
echo "# Auto-generated by install-global.fish — do not edit by hand." > "$FUNC_FILE"
echo "function lyrics-sync --description 'Run Lyrics Sync CLI from anywhere'" >> "$FUNC_FILE"
echo "    \"$SCRIPT_DIR/run.fish\" \$argv" >> "$FUNC_FILE"
echo "end" >> "$FUNC_FILE"

echo ""
echo "==> Done. Open a new fish shell (or run: source $FUNC_FILE)"
echo "    Then, from anywhere, you can run:  lyrics-sync"
