#!/usr/bin/env bash
#
# install-global.sh — Creates a global "lyrics-sync" command so you can
# run the program from ANY terminal/session, without needing to be in
# the project folder, and without creating any daemon or background
# process.
#
# All it does is:
#   1. Create ~/.local/bin/lyrics-sync, a small "bridge" script that
#      points back to this project (uses its venv and its run.sh).
#   2. Make sure ~/.local/bin is on your PATH.
#
# Usage:
#   chmod +x install-global.sh
#   ./install-global.sh
#
# Afterwards, from any new terminal:
#   lyrics-sync

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DIR="$HOME/.local/bin"
LAUNCHER="$BIN_DIR/lyrics-sync"

if [ ! -d "$SCRIPT_DIR/venv" ]; then
    echo "Virtual environment not found at: $SCRIPT_DIR/venv"
    echo "Run ./install.sh inside the project folder first."
    exit 1
fi

mkdir -p "$BIN_DIR"

echo "==> Creating global command at: $LAUNCHER"
cat > "$LAUNCHER" << EOF
#!/usr/bin/env bash
# Auto-generated by install-global.sh — do not edit by hand.
# Runs Lyrics Sync CLI from any session/terminal.
exec "$SCRIPT_DIR/run.sh" "\$@"
EOF

chmod +x "$LAUNCHER"

# Add ~/.local/bin to PATH if it's not already there
if [[ ":$PATH:" != *":$BIN_DIR:"* ]]; then
    LINE='export PATH="$HOME/.local/bin:$PATH"'
    for RC in "$HOME/.bashrc" "$HOME/.zshrc"; do
        if [ -f "$RC" ] && ! grep -Fxq "$LINE" "$RC"; then
            echo "" >> "$RC"
            echo "# Added by install-global.sh (lyrics-sync)" >> "$RC"
            echo "$LINE" >> "$RC"
            echo "==> Added $BIN_DIR to PATH in $RC"
        fi
    done
    echo ""
    echo "==> Open a new terminal (or run 'source ~/.bashrc' / 'source ~/.zshrc')"
    echo "    for the 'lyrics-sync' command to become available."
else
    echo "==> $BIN_DIR was already on PATH."
fi

echo ""
echo "==> Done. From any new terminal you can now run:  lyrics-sync"
